FROM python:latest

WORKDIR /frontendcustomers

COPY admin_app.py .
COPY staticEmployees/ ./staticEmployees
COPY templatesEmployees/ ./templatesEmployees
COPY requirements.txt .
COPY config.ini .
COPY config.py .
COPY .env .env


RUN pip install --no-cache-dir --upgrade -r requirements.txt

EXPOSE 5007

CMD ["gunicorn", "-k", "eventlet", "-w", "1", "-b", "0.0.0.0:5007","--access-logfile", "-", "--error-logfile", "-", "admin_app:app"]
