name: App Pipeline

on:
  push:
    paths:
        - 'app/**'
    branches: [main]  # Adjust to your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Lint Python Code (Backend & Frontend)
      - name: Lint Python Code
        run: |
          pip install ruff
          ruff check backend/
          ruff check frontend/

      # 3. Set image tag using commit SHA
      - name: Set image tag
        id: set_tag
        run: echo "image_tag=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      # 4. Azure Login via OIDC
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 5. Log in to ACR
      - name: ACR Login
        run: az acr login --name crfonteyn001

      # 6. Build & Push Backend Image
      - name: Build & Push Backend (API)
        run: |
          docker build -t crfonteyn001.azurecr.io/fonteyn-booking-app-api:${{ github.sha }} ./backend
          docker push crfonteyn001.azurecr.io/fonteyn-booking-app-api:${{ github.sha }}

      # 7. Build & Push Frontend Image
      - name: Build & Push Frontend
        run: |
          docker build -t crfonteyn001.azurecr.io/fonteyn-booking-app-frontend:${{ github.sha }} ./frontend
          docker push crfonteyn001.azurecr.io/fonteyn-booking-app-frontend:${{ github.sha }}

      # 8. Build & Push Admin Frontend Image
      - name: Build & Push Admin Frontend
        run: |
          docker build -t crfonteyn001.azurecr.io/fonteyn-booking-app-adminfrontend:${{ github.sha }} ./admin
          docker push crfonteyn001.azurecr.io/fonteyn-booking-app-adminfrontend:${{ github.sha }}

      # 9. Trigger Terraform Infra Pipeline
      - name: Trigger Terraform Pipeline
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REPO_DISPATCH_TOKEN }}  # Must be a PAT with repo scope
          event-type: deploy-infra
          client-payload: >-
            {
              "backend_image": "crfonteyn001.azurecr.io/fonteyn-booking-app-api:${{ github.sha }}",
              "frontend_image": "crfonteyn001.azurecr.io/fonteyn-booking-app-frontend:${{ github.sha }}",
              "admin_image": "crfonteyn001.azurecr.io/fonteyn-booking-app-adminfrontend:${{ github.sha }}"
            }
