name: Terraform Deploy to Azure

on:
  push:
    paths:
      - 'infra/**'
    branches:
      - main
  repository_dispatch:
    types: [deploy-infra]

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      BACKEND_IMAGE: ${{ github.event.client_payload.backend_image }}
      FRONTEND_IMAGE: ${{ github.event.client_payload.frontend_image }}
      ADMIN_IMAGE: ${{ github.event.client_payload.admin_image }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login via OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./infra

      - name: Terraform Plan
        run: |
          terraform plan -out=tfplan \
            -var="backend_image=$BACKEND_IMAGE" \
            -var="frontend_image=$FRONTEND_IMAGE" \
            -var="admin_image=$ADMIN_IMAGE"
        working-directory: ./infra

      - name: Show Terraform Plan Output
        run: terraform show -no-color tfplan
        working-directory: ./infra

      - name: Upload Plan File
        uses: actions/upload-artifact@v3.1.3
        with:
          name: terraform-plan
          path: ./infra/tfplan

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform-plan
    environment:
      name: production
      url: https://portal.azure.com

    permissions:
      id-token: write
      contents: read

    env:
      BACKEND_IMAGE: ${{ github.event.client_payload.backend_image }}
      FRONTEND_IMAGE: ${{ github.event.client_payload.frontend_image }}
      ADMIN_IMAGE: ${{ github.event.client_payload.admin_image }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login via OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Download Plan File
        uses: actions/download-artifact@v3.1.3
        with:
          name: terraform-plan
          path: ./infra

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="backend_image=$BACKEND_IMAGE" \
            -var="frontend_image=$FRONTEND_IMAGE" \
            -var="admin_image=$ADMIN_IMAGE"
        working-directory: ./infra
